name: Publish Dev Container Features

on:
  workflow_dispatch:  # Run manually
  push:
    branches: [ main ]  # Or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish features to GHCR
        run: |
          npx -y @devcontainers/cli@latest features publish \
            --namespace ghcr.io/${{ github.repository_owner }} \
            ./src
